name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:


jobs:

  metrics:

    runs-on: ubuntu-latest

    permissions:
      contents: write


    steps:

      - uses: lowlighter/metrics@latest

        with:

          filename: metrics.svg

          token: ${{ secrets.GITHUB_TOKEN }}

          user: Rusiruoshada

          template: classic

          base: header, activity, community, repositories, metadata

          config_timezone: Asia/Colombo

          config_display: large
